baseURL = "https://haiku-inc.org/"
languageCode = "en-us"
title = "Haiku, Inc."
theme = "hugo-smorg"
copyright = "&copy; 2003-2018 Haiku, Inc. All Rights reserved."

[params]
fullname = ""
logotype = "<span class='has-text-weight-bold'>Haiku, <span class='has-text-danger'>Inc.</span></span>"
footer = ""
subfooter = ""

[[menu.sectionmenu]]
	name = "About"
	url = "about/"
[[menu.sectionmenu]]
	name = "FAQ"
	url = "about/faq"
[[menu.sectionmenu]]
	name = "Trademarks"
	url = "about/trademarks"
[[menu.sectionmenu]]
	name = "Documents"
	url = "documents/"
[[menu.sectionmenu]]
	name = "Donate"
	url = "donate/"
[[menu.sectionmenu]]
	name = "Contact"
	url = "contact/"
