baseURL = "https://haiku-inc.org/"
languageCode = "en-us"
title = "Haiku, Inc."
theme = "hugo-smorg"
copyright = "&copy; 2003-2018 Haiku, Inc. All Rights reserved."

[params]
fullname = " "
logotype = "<span class='has-text-weight-bold'>Haiku, <span class='has-text-danger'>Inc.</span></span>"
footer = " "
subfooter = " "

[[menu.sectionmenu]]
	name = "About"
	url = "about/"
	weight = 10
[[menu.sectionmenu]]
	name = "FAQ"
	url = "about/faq"
	weight = 20
[[menu.sectionmenu]]
	name = "Trademarks"
	url = "trademarks/"
	weight = 30
	identifier = "trademarks"
[[menu.sectionmenu]]
	name = "Usage Requirements"
	url = "trademarks/usage_requirements"
	weight = 10
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Allowed Usage"
	url = "trademarks/allowed_usage"
	weight = 20
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Logo Design"
	url = "trademarks/logo_design"
	weight = 30
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Documents"
	url = "documents/"
	identifier = "documents"
	weight = 40
[[menu.sectionmenu]]
	name = "Source code licenses"
	url = "documents/licenses"
	parent = "documents"
	weight = 10
[[menu.sectionmenu]]
	name = "Donation tracking"
	url = "documents/donations"
	parent = "documents"
	weight = 20
[[menu.sectionmenu]]
	name = "Donate"
	url = "donate/"
	weight = 50
[[menu.sectionmenu]]
	name = "Contact"
	url = "contact/"
	weight = 60
